FROM arm32v7/python:3-slim

# Qemu-user-static to build arm image from x86 computer
#ADD https://github.com/multiarch/qemu-user-static/releases/download/v2.12.0/qemu-arm-static /usr/bin/qemu-arm-static
COPY qemu-arm-static /usr/bin/qemu-arm-static

# Install requirements
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy source
COPY app.py .

# Run the application
ENV FLASK_APP=app.py
CMD [ "flask", "run", "--host=0.0.0.0"]