#!/bin/sh
set -e

# Docker Hub client version is: 17.06.2-ee-6
# Use docker-in-docker (18.09.0) in order to use
# experimental features (docker manifest):
# Docker18 requires a different DOCKERCFG

docker18_create()
{
  docker_version="18.09"
  docker create --name=docker18 \
  -e DOCKER_CLI_EXPERIMENTAL=enabled \
  -e DOCKER_HOST=unix:///var/run/docker.sock \
  -e DOCKERCFG="${DOCKERCFG}" \
  -v /var/run/docker.sock:/var/run/docker.sock docker:${docker_version}
}

docker18()
{ 
  commands="$@"
  echo "Running command: docker18 ${commands}"
  docker exec docker18 "${DOCKERCMD}"
}

docker18_create
docker cp "${DOCKERFILE_PATH}" docker18:/"${DOCKERFILE_PATH}"
docker18 build  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
                --build-arg VCS_REF=`git rev-parse --short HEAD` \
                -f /"${DOCKERFILE_PATH}" \
                -t "${IMAGE_NAME}" .

# Check resulting image architecture
echo "[DEBUG] Build finished correctly. Resulting arch:"
docker image inspect "${IMAGE_NAME}" | grep Arch