#!/bin/bash
set -e

#echo "---------- DEBUG ----------"
#echo "Environment variables:"
#printenv

export DOCKER_CLI_EXPERIMENTAL="enabled"

docker manifest --help

# downloads a local copy of qemu on docker-hub build machines
#curl -L https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-arm.tar.gz | tar zxvf - -C . && mv qemu-3.0.0+resin-arm/qemu-arm-static .
curl -L https://github.com/multiarch/qemu-user-static/releases/download/v3.0.0/qemu-arm-static -o qemu-arm-static

# Exec permission
chmod 755 qemu-arm-static